[book]
authors = ["Kaspar Schleiser"]
language = "en"
src = "src"
title = "laze Manual"

[output.html]
git-repository-url = "https://github.com/kaspar030/laze"
edit-url-template = "https://github.com/kaspar030/laze/edit/master/book/{path}"
